function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // o_settings
	global.__objectDepths[1] = 0; // o_skipintro
	global.__objectDepths[2] = 0; // o_skiptutorial
	global.__objectDepths[3] = 0; // o_shopdraw
	global.__objectDepths[4] = 0; // o_title
	global.__objectDepths[5] = 998; // o_backround1
	global.__objectDepths[6] = 999; // o_backround2
	global.__objectDepths[7] = 0; // o_playbutton
	global.__objectDepths[8] = 0; // o_hardbutton
	global.__objectDepths[9] = 0; // oIntro
	global.__objectDepths[10] = -100; // o_closean
	global.__objectDepths[11] = 0; // oHealthSystem
	global.__objectDepths[12] = 0; // oPlayer
	global.__objectDepths[13] = 0; // o_stopintromusic
	global.__objectDepths[14] = 0; // oBullet
	global.__objectDepths[15] = 0; // oBulletAutoGun
	global.__objectDepths[16] = 0; // o_money
	global.__objectDepths[17] = 0; // o_bettermoney
	global.__objectDepths[18] = 0; // o_evenbettermoney
	global.__objectDepths[19] = 0; // o_complete
	global.__objectDepths[20] = 0; // o_smallrock
	global.__objectDepths[21] = 0; // o_rock
	global.__objectDepths[22] = 0; // o_largerock
	global.__objectDepths[23] = 0; // o_hugerock
	global.__objectDepths[24] = 0; // o_explosion
	global.__objectDepths[25] = -15; // o_rockparticle
	global.__objectDepths[26] = -15; // o_rockparticlered
	global.__objectDepths[27] = -15; // o_rockparticlegay
	global.__objectDepths[28] = 0; // o_smallrockred
	global.__objectDepths[29] = 0; // o_rockred
	global.__objectDepths[30] = 0; // o_smallrockgay
	global.__objectDepths[31] = 0; // o_rockgay
	global.__objectDepths[32] = 1; // oTutorialHelper1
	global.__objectDepths[33] = 0; // o_levelbeaten
	global.__objectDepths[34] = 0; // o_achievementsystem
	global.__objectDepths[35] = 0; // o_moneysystem
	global.__objectDepths[36] = 0; // o_playerworld
	global.__objectDepths[37] = 0; // o_meteroidlvl1
	global.__objectDepths[38] = 0; // o_meteroidlvl2
	global.__objectDepths[39] = 0; // o_meteroidlvl3
	global.__objectDepths[40] = 0; // o_meteroidlvl4
	global.__objectDepths[41] = 0; // o_meteroidlvl5
	global.__objectDepths[42] = 0; // o_meteroidlvl6
	global.__objectDepths[43] = 0; // o_meteroidboss1
	global.__objectDepths[44] = 0; // o_meteroidlvl7
	global.__objectDepths[45] = 0; // o_meteroidlvl8
	global.__objectDepths[46] = 0; // o_meteroidlvl9
	global.__objectDepths[47] = 0; // o_meteroidlvl10
	global.__objectDepths[48] = 0; // o_meteroidlvl11
	global.__objectDepths[49] = 0; // o_meteroidlvl12
	global.__objectDepths[50] = 0; // o_meteroidlvl13
	global.__objectDepths[51] = 0; // o_meteroidlvl14
	global.__objectDepths[52] = 0; // o_meteroidboss2
	global.__objectDepths[53] = 0; // o_worldsign
	global.__objectDepths[54] = 0; // o_moneyworld
	global.__objectDepths[55] = 0; // o_music10
	global.__objectDepths[56] = 0; // o_voicedev1
	global.__objectDepths[57] = 0; // o_voicedev2
	global.__objectDepths[58] = 0; // o_voicedev3
	global.__objectDepths[59] = 0; // o_FinishedWorld
	global.__objectDepths[60] = 0; // oLevel1
	global.__objectDepths[61] = 0; // oLevel2
	global.__objectDepths[62] = 0; // oLevel3
	global.__objectDepths[63] = 0; // oLevel4
	global.__objectDepths[64] = 0; // oLevel5
	global.__objectDepths[65] = 0; // oLevel6
	global.__objectDepths[66] = 0; // oLevel7
	global.__objectDepths[67] = 0; // oLevel8
	global.__objectDepths[68] = 0; // oLevel9
	global.__objectDepths[69] = 0; // oLevel10
	global.__objectDepths[70] = 0; // oLevel11
	global.__objectDepths[71] = 0; // oLevel12
	global.__objectDepths[72] = 0; // oLevel13
	global.__objectDepths[73] = 0; // oLevel14
	global.__objectDepths[74] = 0; // oLevelBoss1
	global.__objectDepths[75] = 0; // oLevelBoss2
	global.__objectDepths[76] = 0; // o_FinalRound
	global.__objectDepths[77] = -5; // oHeart
	global.__objectDepths[78] = -5; // o_powericon
	global.__objectDepths[79] = -1; // o_shopenter
	global.__objectDepths[80] = 0; // o_damagebutton
	global.__objectDepths[81] = 0; // o_autogunbutton
	global.__objectDepths[82] = 0; // o_healthbutton
	global.__objectDepths[83] = 0; // o_m1player
	global.__objectDepths[84] = 0; // o_m1maze1
	global.__objectDepths[85] = 0; // o_m1maze2
	global.__objectDepths[86] = 0; // o_m1maze3
	global.__objectDepths[87] = 0; // o_m1pianoman
	global.__objectDepths[88] = 0; // o_talk1
	global.__objectDepths[89] = 0; // o_talk2
	global.__objectDepths[90] = 0; // o_m1entrance
	global.__objectDepths[91] = 0; // oDemo
	global.__objectDepths[92] = 1000; // o_weird1
	global.__objectDepths[93] = 1000; // o_weirdanimation1
	global.__objectDepths[94] = 1000; // o_weirdanimation2
	global.__objectDepths[95] = -1; // o_save
	global.__objectDepths[96] = 0; // o_load
	global.__objectDepths[97] = -1; // o_achievementbutton
	global.__objectDepths[98] = 0; // o_achievement1
	global.__objectDepths[99] = 0; // o_achievement2
	global.__objectDepths[100] = 0; // o_achievement3
	global.__objectDepths[101] = 0; // o_achievement4
	global.__objectDepths[102] = 0; // o_achievement5
	global.__objectDepths[103] = 0; // o_achievement6
	global.__objectDepths[104] = 0; // o_achievement7
	global.__objectDepths[105] = 0; // o_achievement8
	global.__objectDepths[106] = 0; // o_achievement9
	global.__objectDepths[107] = 0; // o_achievement10
	global.__objectDepths[108] = 0; // o_achievement11
	global.__objectDepths[109] = 0; // o_achievement12
	global.__objectDepths[110] = 0; // o_achievement13
	global.__objectDepths[111] = 0; // o_achievement14
	global.__objectDepths[112] = 0; // o_achievement15
	global.__objectDepths[113] = 0; // o_achievement16


	global.__objectNames[0] = "o_settings";
	global.__objectNames[1] = "o_skipintro";
	global.__objectNames[2] = "o_skiptutorial";
	global.__objectNames[3] = "o_shopdraw";
	global.__objectNames[4] = "o_title";
	global.__objectNames[5] = "o_backround1";
	global.__objectNames[6] = "o_backround2";
	global.__objectNames[7] = "o_playbutton";
	global.__objectNames[8] = "o_hardbutton";
	global.__objectNames[9] = "oIntro";
	global.__objectNames[10] = "o_closean";
	global.__objectNames[11] = "oHealthSystem";
	global.__objectNames[12] = "oPlayer";
	global.__objectNames[13] = "o_stopintromusic";
	global.__objectNames[14] = "oBullet";
	global.__objectNames[15] = "oBulletAutoGun";
	global.__objectNames[16] = "o_money";
	global.__objectNames[17] = "o_bettermoney";
	global.__objectNames[18] = "o_evenbettermoney";
	global.__objectNames[19] = "o_complete";
	global.__objectNames[20] = "o_smallrock";
	global.__objectNames[21] = "o_rock";
	global.__objectNames[22] = "o_largerock";
	global.__objectNames[23] = "o_hugerock";
	global.__objectNames[24] = "o_explosion";
	global.__objectNames[25] = "o_rockparticle";
	global.__objectNames[26] = "o_rockparticlered";
	global.__objectNames[27] = "o_rockparticlegay";
	global.__objectNames[28] = "o_smallrockred";
	global.__objectNames[29] = "o_rockred";
	global.__objectNames[30] = "o_smallrockgay";
	global.__objectNames[31] = "o_rockgay";
	global.__objectNames[32] = "oTutorialHelper1";
	global.__objectNames[33] = "o_levelbeaten";
	global.__objectNames[34] = "o_achievementsystem";
	global.__objectNames[35] = "o_moneysystem";
	global.__objectNames[36] = "o_playerworld";
	global.__objectNames[37] = "o_meteroidlvl1";
	global.__objectNames[38] = "o_meteroidlvl2";
	global.__objectNames[39] = "o_meteroidlvl3";
	global.__objectNames[40] = "o_meteroidlvl4";
	global.__objectNames[41] = "o_meteroidlvl5";
	global.__objectNames[42] = "o_meteroidlvl6";
	global.__objectNames[43] = "o_meteroidboss1";
	global.__objectNames[44] = "o_meteroidlvl7";
	global.__objectNames[45] = "o_meteroidlvl8";
	global.__objectNames[46] = "o_meteroidlvl9";
	global.__objectNames[47] = "o_meteroidlvl10";
	global.__objectNames[48] = "o_meteroidlvl11";
	global.__objectNames[49] = "o_meteroidlvl12";
	global.__objectNames[50] = "o_meteroidlvl13";
	global.__objectNames[51] = "o_meteroidlvl14";
	global.__objectNames[52] = "o_meteroidboss2";
	global.__objectNames[53] = "o_worldsign";
	global.__objectNames[54] = "o_moneyworld";
	global.__objectNames[55] = "o_music10";
	global.__objectNames[56] = "o_voicedev1";
	global.__objectNames[57] = "o_voicedev2";
	global.__objectNames[58] = "o_voicedev3";
	global.__objectNames[59] = "o_FinishedWorld";
	global.__objectNames[60] = "oLevel1";
	global.__objectNames[61] = "oLevel2";
	global.__objectNames[62] = "oLevel3";
	global.__objectNames[63] = "oLevel4";
	global.__objectNames[64] = "oLevel5";
	global.__objectNames[65] = "oLevel6";
	global.__objectNames[66] = "oLevel7";
	global.__objectNames[67] = "oLevel8";
	global.__objectNames[68] = "oLevel9";
	global.__objectNames[69] = "oLevel10";
	global.__objectNames[70] = "oLevel11";
	global.__objectNames[71] = "oLevel12";
	global.__objectNames[72] = "oLevel13";
	global.__objectNames[73] = "oLevel14";
	global.__objectNames[74] = "oLevelBoss1";
	global.__objectNames[75] = "oLevelBoss2";
	global.__objectNames[76] = "o_FinalRound";
	global.__objectNames[77] = "oHeart";
	global.__objectNames[78] = "o_powericon";
	global.__objectNames[79] = "o_shopenter";
	global.__objectNames[80] = "o_damagebutton";
	global.__objectNames[81] = "o_autogunbutton";
	global.__objectNames[82] = "o_healthbutton";
	global.__objectNames[83] = "o_m1player";
	global.__objectNames[84] = "o_m1maze1";
	global.__objectNames[85] = "o_m1maze2";
	global.__objectNames[86] = "o_m1maze3";
	global.__objectNames[87] = "o_m1pianoman";
	global.__objectNames[88] = "o_talk1";
	global.__objectNames[89] = "o_talk2";
	global.__objectNames[90] = "o_m1entrance";
	global.__objectNames[91] = "oDemo";
	global.__objectNames[92] = "o_weird1";
	global.__objectNames[93] = "o_weirdanimation1";
	global.__objectNames[94] = "o_weirdanimation2";
	global.__objectNames[95] = "o_save";
	global.__objectNames[96] = "o_load";
	global.__objectNames[97] = "o_achievementbutton";
	global.__objectNames[98] = "o_achievement1";
	global.__objectNames[99] = "o_achievement2";
	global.__objectNames[100] = "o_achievement3";
	global.__objectNames[101] = "o_achievement4";
	global.__objectNames[102] = "o_achievement5";
	global.__objectNames[103] = "o_achievement6";
	global.__objectNames[104] = "o_achievement7";
	global.__objectNames[105] = "o_achievement8";
	global.__objectNames[106] = "o_achievement9";
	global.__objectNames[107] = "o_achievement10";
	global.__objectNames[108] = "o_achievement11";
	global.__objectNames[109] = "o_achievement12";
	global.__objectNames[110] = "o_achievement13";
	global.__objectNames[111] = "o_achievement14";
	global.__objectNames[112] = "o_achievement15";
	global.__objectNames[113] = "o_achievement16";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
